import type { CSSProperties } from "react";

export const loyaltyStyles: Record<string, CSSProperties> = {
  page: {
    padding: "40px 32px 32px",
    background: "#f7f9fb",
    minHeight: "100vh",
    maxWidth: 1240,
    margin: "0 auto",
    fontFamily: "Inter, system-ui, sans-serif",
  },
  header: {
    padding: "0 0 24px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 16,
  },
  title: {
    margin: 0,
    fontSize: 30,
    lineHeight: "34px",
    fontWeight: 800,
    color: "#0f172a",
    fontFamily: "Manrope, Inter, system-ui, sans-serif",
  },
  subtitle: { margin: "6px 0 0", fontSize: 14, color: "#64748b", fontWeight: 500 },
  primaryActionBtn: {
    background: "#009661",
    color: "#fff",
    border: "none",
    borderRadius: 12,
    padding: "11px 20px",
    fontSize: 14,
    fontWeight: 700,
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    boxShadow: "0 10px 28px rgba(0,150,97,0.25)",
  },
  tabs: {
    display: "flex",
    gap: 20,
    marginBottom: 24,
    borderBottom: "1px solid #dbe1e6",
    overflowX: "auto",
  },
  tab: {
    padding: "0 6px 14px",
    border: "none",
    cursor: "pointer",
    fontSize: 14,
    fontWeight: 600,
    background: "transparent",
    color: "#64748b",
    transition: "all 0.2s",
    whiteSpace: "nowrap",
  },
  tabActive: {
    color: "#009661",
    borderBottom: "2px solid #009661",
    marginBottom: -1,
  },
  searchWrap: {
    position: "relative",
    maxWidth: 420,
    marginBottom: 24,
  },
  searchIcon: {
    position: "absolute",
    left: 14,
    top: "50%",
    transform: "translateY(-50%)",
    color: "#009661",
    opacity: 0.65,
  },
  searchInput: {
    width: "100%",
    padding: "12px 14px 12px 40px",
    borderRadius: 12,
    fontSize: 14,
    border: "1px solid #d5dbe2",
    outline: "none",
    background: "#fff",
    boxSizing: "border-box",
  },
  errorBox: {
    background: "#fef2f2",
    border: "1px solid #fecaca",
    borderRadius: 6,
    padding: "12px 16px",
    color: "#b91c1c",
    marginBottom: 16,
    fontSize: 14,
  },
  empty: {
    textAlign: "center",
    padding: "80px 0",
    color: "#94a3b8",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 12,
  },
  cardGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(280px, 1fr))", gap: 18 },
  franchiseSection: {
    marginBottom: 28,
    background: "#fff",
    borderRadius: 16,
    border: "1px solid #edf1f4",
    boxShadow: "0 4px 20px rgba(15,23,42,0.04)",
    padding: 20,
  },
  franchiseHeader: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    marginBottom: 16,
    paddingBottom: 14,
    borderBottom: "1px solid #eef2f5",
  },
  franchiseIcon: { fontSize: 18 },
  franchiseTitle: { margin: 0, fontSize: 17, fontWeight: 700, color: "#0f172a", flex: 1 },
  franchiseCount: {
    background: "#009661",
    color: "#fff",
    borderRadius: 20,
    padding: "4px 12px",
    fontSize: 12,
    fontWeight: 600,
    whiteSpace: "nowrap",
  },
  card: {
    background: "#fff",
    borderRadius: 12,
    padding: 18,
    border: "1px solid #edf1f4",
    boxShadow: "0 2px 10px rgba(15,23,42,0.05)",
  },
  cardHeader: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 16 },
  cardActions: { display: "flex", gap: 8 },
  badge: { padding: "4px 12px", borderRadius: 20, fontSize: 12, fontWeight: 700, letterSpacing: 1 },
  statRow: { display: "flex", justifyContent: "space-between", marginBottom: 8 },
  statLabel: { fontSize: 13, color: "#6b7280" },
  statValue: { fontSize: 14, fontWeight: 600, color: "#1a1a1a" },
  benefitText: { fontSize: 13, color: "#374151", margin: "4px 0 0" },
  tableContainer: {
    background: "#fff",
    borderRadius: 16,
    border: "1px solid #edf1f4",
    boxShadow: "0 4px 20px rgba(15,23,42,0.04)",
    overflowX: "auto",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
  },
  th: {
    background: "#f2f4f6",
    padding: "14px 16px",
    textAlign: "left",
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: 0.9,
    textTransform: "uppercase",
    color: "#596171",
    borderBottom: "1px solid #e5e7eb",
  },
  tr: { borderBottom: "1px solid #eef2f5" },
  td: { padding: "16px", fontSize: 14, color: "#334155", verticalAlign: "middle" },
  eventBadge: {
    padding: "4px 11px",
    borderRadius: 999,
    fontSize: 12,
    fontWeight: 600,
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
  },
  statusBadge: {
    padding: "5px 11px",
    borderRadius: 999,
    fontSize: 12,
    fontWeight: 700,
    display: "inline-flex",
    alignItems: "center",
  },
  overlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.4)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
  },
  modal: {
    background: "#fff",
    borderRadius: 14,
    padding: 28,
    width: "100%",
    maxWidth: 520,
    boxShadow: "0 20px 60px rgba(0,0,0,0.15)",
  },
  modalHeader: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 24 },
  modalTitle: { margin: 0, fontSize: 18, fontWeight: 700 },
  closeBtn: { background: "none", border: "none", fontSize: 18, cursor: "pointer", color: "#6b7280" },
  modalFooter: { display: "flex", justifyContent: "flex-end", gap: 12, marginTop: 24 },
  formGroup: { marginBottom: 16 },
  label: { display: "block", fontSize: 13, fontWeight: 600, color: "#374151", marginBottom: 6 },
  input: {
    width: "100%",
    padding: "10px 12px",
    borderRadius: 10,
    fontSize: 14,
    border: "1px solid #d1d5db",
    outline: "none",
    boxSizing: "border-box",
    fontFamily: "inherit",
  },
  btnPrimary: {
    background: "#009661",
    color: "#fff",
    border: "none",
    borderRadius: 10,
    padding: "10px 20px",
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
  },
  btnSecondary: {
    background: "#f3f4f6",
    color: "#374151",
    border: "none",
    borderRadius: 10,
    padding: "10px 20px",
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
  },
  btnEdit: {
    background: "#f0fdf4",
    color: "#009661",
    border: "none",
    borderRadius: 8,
    padding: "5px 12px",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
  },
  btnDelete: {
    background: "#fef2f2",
    color: "#ef4444",
    border: "none",
    borderRadius: 8,
    padding: "5px 12px",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
  },
};
